name: Integration Tests

on:
  push:
    branches: [ main, tests ]
  pull_request:
    branches: [ main ]
    paths:
      - 'llama_stack/**'
      - 'tests/integration/**'
      - 'uv.lock'
      - 'pyproject.toml'
      - 'requirements.txt'
      - '.github/workflows/integration-tests.yml' # This workflow
  schedule:
    - cron: '0 0 * * *'  # Daily at 12 AM UTC
    - cron: '53 8 * * *'  # Weekly on Sunday at 8:50 AM UTC
  workflow_dispatch:
    inputs:
      test-all-client-versions:
        description: 'Test against both the latest and published versions'
        type: boolean
        default: false
      test-provider:
        description: 'Test against a specific provider'
        type: string
        default: 'ollama'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        client-type: [library, client]
        # Use vllm on weekly schedule, otherwise use test-provider input (defaults to ollama)
        provider: ${{ (github.event.schedule == '50 8 * * *') && fromJSON('["vllm"]') || fromJSON(format('["{0}"]', github.event.inputs.test-provider || 'ollama')) }}
        client-version: ${{ (github.event.schedule == '0 0 * * 0' || github.event.inputs.test-all-client-versions == 'true') && fromJSON('["published", "latest"]') || fromJSON('["latest"]') }}
    steps:
      - name: test
        if: ${{ always() }}
        run: |
          echo "client-type: ${{ matrix.client-type }}"
          echo "provider: ${{ matrix.provider }}"
          echo "test-provider: ${{ github.event.inputs.test-provider }}"
          echo "schedule: ${{ github.event.schedule }}"
          echo "event: ${{ github.event_name }}"
          echo "test-all-client-versions: ${{ github.event.inputs.test-all-client-versions }}"
          echo "client-version: ${{ matrix.client-version }}"
          echo "================================================"
          env
