name: Verification Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - 'llama_stack/**'
      - 'tests/verifications/**'
      - 'uv.lock'
      - 'pyproject.toml'
      - 'requirements.txt'
      - '.github/workflows/verification-tests.yml' # This workflow
  schedule:
    - cron: '15 4 * * *' # Ensure the cache is accessed (so its not zapped)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-type: [openai]

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@c7f87aa956e4c323abf06d5dec078e358f6b4d04 # v6.0.0
        with:
          python-version: "3.10"
          activate-environment: true

      # TODO: some kind of pruning is required to prevent cache growing endlessly
      - uses: actions/cache@v4
        with:
          path: /home/runner/.cache/cachemeifyoucan
          key: http-cache-${{ github.sha }}
          restore-keys:
            http-cache-

      - name: Set Up Environment and Install Dependencies
        run: |
          uv pip install -r requirements.txt pytest pytest-json-report
          uv pip install -e .

          uv pip install git+https://github.com/derekhiggins/cachemeifyoucan.git@69cd438
          echo -e 'openai:\n  url: https://api.openai.com/v1' > cachemeifyoucan.yaml
          nohup uv run uvicorn cachemeifyoucan:app --host 127.0.0.1 --port 9999 > cachemeifyoucan.log 2>&1 &

      - name: Run the job
        id: run
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_KEY }}
        run: |
          sed -i 's%base_url: .*%base_url: http://localhost:9999/openai%g' tests/verifications/conf/openai.yaml
          uv run pytest tests/verifications/openai_api --provider=openai -vvv

      - name: gather artifacts
        # always run this step
        continue-on-error: true
        run: |
          mkdir -p /tmp/artifacts
          cp cachemeifyoucan.log /tmp/artifacts
          cp -r /home/runner/.cache/cachemeifyoucan /tmp/artifacts

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cachemeifyoucan
          path: /tmp/artifacts
